version: '3.8'
services:
  app:
    image: your-docker-image:latest
    container_name: myapp
    environment:
      - SPRING_PROFILES_ACTIVE=${ENVIRONMENT}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
