spring:
  main:
    banner-mode: "off"
  application:
    name: gestaoResiduos
  flyway:
    baselineOnMigrate: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;MODE=MySQL;DATABASE_TO_UPPER=true;
    username: sa
    password: sa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: gestaoResiduos
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
      percentiles: [0.5, 0.9, 0.95]