CREATE TABLE IF NOT EXISTS TBL_CAMINHAO (
    "CAMINHAO_ID" BIGINT UNIQUE AUTO_INCREMENT,
    "MODELO" VARCHAR2(50),
    "CAPACIDADE_MAXIMA_LITROS" NUMBER(6,2),
    "STATUS" BOOLEAN,
    PRIMARY KEY("CAMINHAO_ID")
);

CREATE TABLE IF NOT EXISTS TBL_RECIPIENTE (
    "RECIPIENTE_ID" INTEGER UNIQUE AUTO_INCREMENT,
    "VOLUME_ATUAL_LITROS" NUMBER(6,2),
    "VOLUME_TOTAL_LITROS" NUMBER(6,2),
    "STATUS" VARCHAR2(20),
    PRIMARY KEY("RECIPIENTE_ID")
);