name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente de execução, você pode escolher ubuntu-latest ou outros

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

   # Etapa 2: Configuração do JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3  # Usando a versão mais recente do setup-java
      with:
        java-version: '17'          # Especifica a versão do Java (17)
        distribution: 'adoptopenjdk'  # Usando o adoptopenjdk (ou openjdk)
        java-package: 'jdk'         # Pacote JDK
        architecture: 'x64'         # Arquitetura 64-bit
        check-latest: false         # Não verificar por versões mais recentes

    # Etapa 2: Instalar manualmente o JDK (caso a configuração não funcione)
    - name: Install JDK 21 (manual installation)
      run: |
        sudo apt update
        sudo apt install -y openjdk-21-jdk
        java -version  # Verificar se a instalação foi bem-sucedida

    # Etapa 3: Limpeza de cache (opcional, mas recomendado para evitar problemas)
    - name: Clean cache
      run: |
        sudo rm -rf ~/.m2/repository  # Limpa o cache do Maven
        sudo rm -rf ~/.gradle         # Limpa o cache do Gradle

    # Etapa 4: Verificar dependências (opcional)
    - name: Verify dependencies
      run: |
        mvn clean install             # Use seu gerenciador de dependências (Maven/Gradle)
        # Caso esteja usando Gradle, substitua com: gradle clean build

    # Etapa 5: Build do projeto
    - name: Build project with Maven
      run: mvn clean install  # Comando Maven para compilar o projeto

  
    # Etapa 7: Deploy (caso seja necessário, configure seu processo de deployment)
    - name: Deploy to Staging
      run: |
        echo "Deploying to staging environment..."  # Substitua com seu processo de deploy real

    - name: Deploy to Production
      run: |
        echo "Deploying to production environment..."  # Substitua com seu processo de deploy real
