name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Utilize a distribuição temurin que é bem suportada
          java-version: '17'

      - name: Verify Java version
        run: java -version

      # Continue with your build steps...

