name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Distribuição Temurin
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Set environment variable
        run: echo "ENVIRONMENT=staging" >> $GITHUB_ENV


      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Start Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run tests inside Docker container
        run: |
          docker-compose exec app mvn test

      - name: Shut down Docker Compose
        run: |
          docker-compose down