name: CI/CD Pipeline

# Define os eventos que vão disparar o workflow
on:
  push:
    branches:
      - main    # Para produção
      - staging # Para staging
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:  # Para executar manualmente
    inputs:
      environment:
        description: 'Choose environment: staging or production'
        required: true
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
      - name: Build with Maven
        run: mvn clean install

  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Deploy to Staging
        run: |
          ENVIRONMENT=staging docker-compose up -d --build

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        run: |
          ENVIRONMENT=production docker-compose up -d --build

