name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ou a branch que você usa para produção

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'            # A versão do JDK
        distribution: 'zulu'       # Distribuição do JDK (openjdk, adoptopenjdk, zulu, oracle)
        java-package: 'jdk'           # Pacote JDK (jdk ou jre)
        architecture: 'x64'           # Arquitetura x64
        check-latest: false           # Não verifica por versões mais recentes


    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker image
      run: docker build -t nome-da-imagem .

    - name: Push Docker image
      run: docker push nome-da-imagem

    - name: Deploy to Staging
      run: |
        # Comandos para fazer o deploy no ambiente de staging
        docker run -d -p 8080:8080 nome-da-imagem

    - name: Deploy to Production
      run: |
        # Comandos para fazer o deploy no ambiente de produção
        docker run -d -p 8080:8080 nome-da-imagem
