name: Java CI with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Etapa 1: Checkout do código
    - name: Checkout code
      uses: actions/checkout@v2

    # Etapa 2: Configuração do JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.6'
        distribution: 'openjdk'
        java-package: 'jdk'
        architecture: 'x64'

    # Etapa 3: Build do projeto com Maven
    - name: Build project with Maven
      run: mvn clean install

    # Etapa 4: Build da imagem Docker
    - name: Build Docker image
      run: docker-compose build

    # Etapa 5: Subir a imagem para o Docker Hub (ou GitHub Container Registry)
    - name: Push Docker image
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker-compose push
