uses: actions/setup-java@v2.5.0
name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'            # A versão do JDK
        distribution: 'openjdk'       # Distribuição do JDK

